# 이 파일은 Ceph RBD (Block Device) StorageClass를 정의.
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: replicapool
  namespace: rook-ceph
spec:
  failureDomain: host
  replicated:
    size: 3 # 데이터 복제본 수. 스토리지 노드가 3개라면 3으로 설정.
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rook-ceph-block
  # 이 StorageClass를 기본(default)으로 설정하고 싶다면 아래 주석을 해제.
  # annotations:
  #   storageclass.kubernetes.io/is-default-class: "true"
provisioner: rook-ceph.rbd.csi.ceph.com
parameters:
  pool: replicapool
  clusterID: rook-ceph-cluster
  imageFeatures: "layering"
  csi.storage.k8s.io/fstype: xfs
reclaimPolicy: Retain
allowVolumeExpansion: true
