# k8s-infra-as-code/kubernetes-addons/rook-ceph/rook-ceph/values.yaml
# -- 이 파일은 Helm Chart의 기본 설정과 커스텀 설정을 모두 포함한다. --
image:
  repository: quay.io/rook/ceph # <-- 공식 이미지 저장소로 수정
  tag: v1.18.9
  pullPolicy: IfNotPresent
crds:
  enabled: true
resources:
  limits:
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 128Mi
nodeSelector: {}
tolerations: []
unreachableNodeTolerationSeconds: 5
currentNamespaceOnly: false
operatorPodLabels: {}
annotations: {}
logLevel: INFO
rbacEnable: true
rbacAggregate:
  enableOBCs: false
pspEnable: false
priorityClassName:
containerSecurityContext:
  runAsNonRoot: true
  runAsUser: 2016
  runAsGroup: 2016
  capabilities:
    drop: ["ALL"]
allowLoopDevices: false
# -- CSI 드라이버 및 사이드카 설정 --
csi:
  enableRbdDriver: true
  enableCephfsDriver: true
  disableCsiDriver: "false"
  enableCSIHostNetwork: true
  enableCephfsSnapshotter: true
  enableNFSSnapshotter: true
  enableRBDSnapshotter: true
  enablePluginSelinuxHostMount: false
  enableCSIEncryption: false
  enableVolumeGroupSnapshot: true
  pluginPriorityClassName: system-node-critical
  provisionerPriorityClassName: system-cluster-critical
  rbdFSGroupPolicy: "File"
  cephFSFSGroupPolicy: "File"
  nfsFSGroupPolicy: "File"
  enableOMAPGenerator: false
  cephFSKernelMountOptions:
  enableMetadata: false
  provisionerReplicas: 2
  clusterName:
  logLevel: 0
  sidecarLogLevel:
  csiDriverNamePrefix:
  rbdPluginUpdateStrategy:
  rbdPluginUpdateStrategyMaxUnavailable:
  cephFSPluginUpdateStrategy:
  cephFSPluginUpdateStrategyMaxUnavailable:
  nfsPluginUpdateStrategy:
  grpcTimeoutInSeconds: 150
  kubeApiBurst:
  kubeApiQPS:
  csiRBDPluginVolume:
  csiRBDPluginVolumeMount:
  csiCephFSPluginVolume:
  csiCephFSPluginVolumeMount:
  csiRBDProvisionerResource: |
    - name : csi-provisioner
      resource:
        requests:
          memory: 128Mi
          cpu: 100m
        limits:
          memory: 256Mi
    - name : csi-resizer
      resource:
        requests:
          memory: 128Mi
          cpu: 100m
        limits:
          memory: 256Mi
    - name : csi-attacher
      resource:
        requests:
          memory: 128Mi
          cpu: 100m
        limits:
          memory: 256Mi
    - name : csi-snapshotter
      resource:
        requests:
          memory: 128Mi
          cpu: 100m
        limits:
          memory: 256Mi
    - name : csi-rbdplugin
      resource:
        requests:
          memory: 512Mi
        limits:
          memory: 1Gi
    - name : csi-omap-generator
      resource:
        requests:
          memory: 512Mi
          cpu: 250m
        limits:
          memory: 1Gi
    - name : liveness-prometheus
      resource:
        requests:
          memory: 128Mi
          cpu: 50m
        limits:
          memory: 256Mi
    - name : driver-registrar
      resource:
        requests:
          memory: 128Mi
          cpu: 50m
        limits:
          memory: 256Mi
    - name : csi-rbdplugin
      resource:
        requests:
          memory: 512Mi
          cpu: 250m
        limits:
          memory: 1Gi
    - name : liveness-prometheus
      resource:
        requests:
          memory: 128Mi
          cpu: 50m
        limits:
          memory: 256Mi
    - name : csi-provisioner
      resource:
        requests:
          memory: 128Mi
          cpu: 100m
        limits:
          memory: 256Mi
    - name : csi-resizer
      resource:
        requests:
          memory: 128Mi
          cpu: 100m
        limits:
          memory: 256Mi
    - name : csi-attacher
      resource:
        requests:
          memory: 128Mi
          cpu: 100m
        limits:
          memory: 256Mi
    - name : csi-snapshotter
      resource:
        requests:
          memory: 128Mi
          cpu: 100m
        limits:
          memory: 256Mi
    - name : csi-cephfsplugin
      resource:
        requests:
          memory: 512Mi
          cpu: 250m
        limits:
          memory: 1Gi
    - name : liveness-prometheus
      resource:
        requests:
          memory: 128Mi
          cpu: 50m
        limits:
          memory: 256Mi
    - name : csi-provisioner
      resource:
        requests:
          memory: 128Mi
          cpu: 100m
        limits:
          memory: 256Mi
    - name : csi-nfsplugin
      resource:
        requests:
          memory: 512Mi
          cpu: 250m
        limits:
          memory: 1Gi
    - name : csi-attacher
      resource:
        requests:
          memory: 512Mi
          cpu: 250m
        limits:
          memory: 1Gi
    - name : driver-registrar
      resource:
        requests:
          memory: 128Mi
          cpu: 50m
        limits:
          memory: 256Mi
    - name : csi-nfsplugin
      resource:
        requests:
          memory: 512Mi
          cpu: 250m
        limits:
          memory: 1Gi
    - name : liveness-prometheus
      resource:
        requests:
          memory: 128Mi
          cpu: 50m
        limits:
          memory: 256Mi
  nfs:
    enabled: false
  cephFSAttachRequired: true
  rbdAttachRequired: true
  nfsAttachRequired: true
enableDiscoveryDaemon: false
discoverDaemonInterval: 60m
cephCommandsTimeoutSeconds: "15"
useOperatorHostNetwork:
scaleDownOperator: false
disableDeviceHotplug: false
revisionHistoryLimit:
discoverDaemonUdev:
imagePullSecrets:
enableOBCWatchOperatorNamespace: true
obcProvisionerNamePrefix:
obcAllowAdditionalConfigFields: "maxObjects,maxSize"
monitoring:
  enabled: false
# --- [ 추가된 커스텀 설정 시작 ] ---
# -- Ceph 클러스터 정의 (CephCluster CRD) --
cephClusterSpec:
  cephVersion:
    image: "quay.io/ceph/ceph:v18.2.4"
  dataDirHostPath: /var/lib/rock
  mon:
    count: 3
    allowMultiplePerNode: true
  storage:
    useAllNodes: true
    useAllDevices: false
    deviceFilter: "sdb"
    resources:
      limits:
        cpu: "500m"
        memory: "1Gi"
      requests:
        cpu: "100m"
        memory: "512Mi"
# -- Ceph Block Pool 정의 (CephBlockPool CRD) --
cephBlockPools:
  - name: replicapool
    namespace: rock-ceph
    replicated:
      size: 3
    failureDomain: host
# -- StorageClass 정의 --
storageClass:
  enabled: true
  name: rock-ceph-block
  reclaimPolicy: Retain
  allowVolumeExpansion: true
  mountOptions: []
  parameters:
    pool: replicapool
    clusterID: rock-ceph-cluster
    imageFeatures: layering
    csi.storage.k8s.io/fstype: xfs
