# ====================================================================
#  [최후의 수정본] 확인된 데이터만 사용하고, fsid 참조를 완전히 제거하여
#  모든 'FailedMount' 오류를 원천적으로 해결하는 최종 버전입니다.
# ====================================================================
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-ceph-tools
  namespace: rook-ceph
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rook-ceph-tools-role
  namespace: rook-ceph
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rook-ceph-tools-binding
  namespace: rook-ceph
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rook-ceph-tools-role
subjects:
- kind: ServiceAccount
  name: rook-ceph-tools
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rook-ceph-tools
  namespace: rook-ceph
  labels:
    app: rook-ceph-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rook-ceph-tools
  template:
    metadata:
      labels:
        app: rook-ceph-tools
    spec:
      dnsPolicy: ClusterFirst
      serviceAccountName: rook-ceph-tools
      containers:
      - name: rook-ceph-tools
        image: quay.io/ceph/ceph:v18.2.7
        command: ["/bin/sleep", "infinity"]
        volumeMounts:
          - name: ceph-config-dir
            mountPath: /etc/ceph
      initContainers:
      - name: init-ceph-config
        image: quay.io/ceph/ceph:v18.2.7
        command: ["/bin/bash", "-c"]
        args:
        - |
          set -ex
          # [수정] mon 엔드포인트만 가져옵니다.
          MON_ENDPOINTS_WITH_NAMES=$(cat /etc/rook-config/mon-endpoints)
          MON_ENDPOINTS=$(echo "${MON_ENDPOINTS_WITH_NAMES}" | sed 's/[a-z0-9_-]\+=//g')

          # [수정] admin key만 가져옵니다.
          ADMIN_KEY=$(cat /etc/rook-admin-keyring/keyring)

          # [수정] fsid 없이 mon_host만으로 ceph.conf 파일을 생성합니다.
          cat << EOF > /etc/ceph-out/ceph.conf
          [global]
          mon_host = ${MON_ENDPOINTS}
          EOF

          # [수정] ceph.client.admin.keyring 파일은 그대로 생성합니다.
          cat << EOF > /etc/ceph-out/ceph.client.admin.keyring
          [client.admin]
          key = ${ADMIN_KEY}
          caps mds = "allow *"
          caps mon = "allow *"
          caps osd = "allow *"
          caps mgr = "allow *"
          EOF
        volumeMounts:
          - name: ceph-config-dir
            mountPath: /etc/ceph-out
          - name: mon-endpoints-volume
            mountPath: /etc/rook-config
          - name: admin-keyring-volume
            mountPath: /etc/rook-admin-keyring
      volumes:
        - name: ceph-config-dir
          emptyDir: {}
        # [수정] mon-endpoints ConfigMap에서는 'data' 키만 참조합니다.
        - name: mon-endpoints-volume
          configMap:
            name: rook-ceph-mon-endpoints
            items:
              - key: data
                path: mon-endpoints
        # [수정] fsid-volume 부분을 완전히 삭제했습니다.
        # [수정] admin-keyring Secret에서는 'keyring' 키만 참조합니다.
        - name: admin-keyring-volume
          secret:
            secretName: rook-ceph-admin-keyring
            items:
              - key: keyring
                path: keyring
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
