apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    # Ceph v18.2.7 (Reef) 버전을 사용합니다.
    image: quay.io/ceph/ceph:v18.2.7
  
  dataDirHostPath: /var/lib/rook

  mon:
    count: 3
    # [중요] 사용 가능한 노드가 2대이므로, 하나의 노드에 여러 개의 mon이 배치될 수 있도록 허용.
    allowMultiplePerNode: true
  
  mgr:
    count: 2
    allowMultiplePerNode: false
        
  dashboard:
    enabled: true
    ssl: true
  
  monitoring:
    enabled: false

  crashCollector:
    disable: false

  storage:
    # [수정] true로 설정하여 모든 노드에서 sdb 디스크를 찾음.
    useAllNodes: true
    # [수정] false로 설정하여 모든 디스크를 자동으로 사용하는 것을 방지.
    useAllDevices: false
    # [수정] 'sdb' 라는 이름의 디스크만 OSD로 사용하도록 정확히 지정.
    deviceFilter: "sdb"

  disruptionManagement:
    managePodBudgets: true
    
  resources:
    osd:
      limits:
        cpu: "500m"
        memory: "1Gi"
      requests:
        cpu: "100m"
        memory: "512Mi"

  priorityClassNames:
    mon: system-node-critical
    osd: system-node-critical
    mgr: system-cluster-critical

  healthCheck:
    daemonHealth:
      mon:
        disabled: false
        interval: 45s
      osd:
        disabled: false
        interval: 60s
      status:
        disabled: false
        interval: 60s
