apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    # [가장 중요] Ceph 이미지 버전을 v18.2.2로 변경하여 환경 호환성 문제를 해결합니다.
    image: quay.io/ceph/ceph:v18.2.2
  
  dataDirHostPath: /var/lib/rook
  mon:
    count: 1
    allowMultiplePerNode: true
  mgr:
    count: 1
  dashboard:
    enabled: true
    ssl: true
  placement:
    osd:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/master
              operator: DoesNotExist
            - key: node-role.kubernetes.io/control-plane
              operator: DoesNotExist
  storage:
    useAllNodes: false
    nodes:
    - name: "k8s-node-01"
      config:
        deviceFilter: "sdb"
  # ... (이전 파일의 resources, priorityClassNames 등 나머지 설정은 그대로 유지) ...
  disruptionManagement:
    managePodBudgets: true
  resources:
    osd:
      limits:
        cpu: "500m"
        memory: "1Gi"
      requests:
        cpu: "100m"
        memory: "512Mi"
  priorityClassNames:
    mon: system-node-critical
    osd: system-node-critical
    mgr: system-cluster-critical
