apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: quay.io/ceph/ceph:v18.2.7
  
  dataDirHostPath: /var/lib/rook

  mon:
    count: 2
    allowMultiplePerNode: true
  
  mgr:
    count: 2
    allowMultiplePerNode: false
        
  dashboard:
    enabled: true
    ssl: true
  
  monitoring:
    enabled: false

  # [중요] mon과 osd의 placement 설정 추가
  placement:
    mon:
      # 마스터 노드의 'NoSchedule' 테인트를 용인(tolerate)하도록 설정
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
    osd:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            # OSD는 마스터 노드를 제외하고 배치
            - key: node-role.kubernetes.io/master
              operator: DoesNotExist
            - key: node-role.kubernetes.io/control-plane
              operator: DoesNotExist

  storage:
    useAllNodes: true
    useAllDevices: false
    deviceFilter: "sdb"

  disruptionManagement:
    managePodBudgets: true
    
  resources:
    osd:
      limits:
        cpu: "500m"
        memory: "1Gi"
      requests:
        cpu: "100m"
        memory: "512Mi"

  priorityClassNames:
    mon: system-node-critical
    osd: system-node-critical
    mgr: system-cluster-critical

  healthCheck:
    daemonHealth:
      mon:
        disabled: false
        interval: 45s
      osd:
        disabled: false
        interval: 60s
      status:
        disabled: false
        interval: 60s
